import type { InjectionKey } from 'vue'
import type { TSynchData } from '../interface'

export const keySynchData = Symbol() as InjectionKey<TSynchData>

export const PRODUCT_DEFAULT = {
  cost: 0,
  product_id: '',
  product_name: '',
  type: 'product',
  status: 'ACTIVE',
  custom_fields: {
    revenue_allocation: false,
    commission_allocation: false,
    value_gradually_decreases: null,
    departments_allocated_commissions: [],
    calculate_commission_for_marketing: false,
  },
  price: 0,
  wholesale_price: 0,
  vat: 0,
  service_fee: null,
  max_inventory_quantity: 0,
  min_inventory_quantity: 0,
  sold_when_quantity_runs_out: false,
  weight: 0,
  length: 0,
  width: 0,
  height: 0,
  images: [],
  quantity: 1,
  discount: 0,
  total_price: 0,
}

export const INIT_ORDER = {
  products: [],
  quantity: 0,
  price: 0,
  discount: 0,
  vat: 0,
  total_price: 0,
  total_money: 0,
  money_paid: 0,
  money_back: 0,
  money_proceeds: 0,
  money_unpaid: 0,
  save_in_debt: false,
  payment_method: '',
  cashier: '',
  note: '',
  status: '',
  // contact_id: $merchant.contact?.identifier_id,
  contact_info: {},
  other_costs: [],
  total_other_costs: 0,
  images: [],
  // address: !$appStore.is_auto_create ? $merchant.orders?.[0]?.address : '',
  is_freeship: false,
  internal_note: '',
  internal_images: [],
  created_date: new Date(),
  custom_fields: {
    sales_channel: 'online',
    source: 'Facebook',
    // page_id: $appStore.data_client?.public_profile?.page_id || '',
    master: '',
    assistant: '',
    last_phone: '',
    customer_name: '',
    // fb_client_id: $appStore.data_client?.public_profile?.fb_client_id || '',
  },
  locations: {},
  // locations: !$appStore.is_auto_create
  //   ? JSON.parse(JSON.stringify($merchant.orders?.[0]?.locations || {}))
  //   : {},
  // order_journey: $merchant.setting?.online_status || [],
  // staffs: $merchant.setting?.online_staff || [],
  inventory_quantity: 0,
}

export const PROVINCE = [
  {
    name: 'Lào Cai',
    slug: 'lao-cai',
    type: 'tinh',
    name_with_type: 'Tỉnh Lào Cai',
    code: '10',
  },
  {
    name: 'Điện Biên',
    slug: 'dien-bien',
    type: 'tinh',
    name_with_type: 'Tỉnh Điện Biên',
    code: '11',
  },
  {
    name: 'Lai Châu',
    slug: 'lai-chau',
    type: 'tinh',
    name_with_type: 'Tỉnh Lai Châu',
    code: '12',
  },
  {
    name: 'Sơn La',
    slug: 'son-la',
    type: 'tinh',
    name_with_type: 'Tỉnh Sơn La',
    code: '14',
  },
  {
    name: 'Yên Bái',
    slug: 'yen-bai',
    type: 'tinh',
    name_with_type: 'Tỉnh Yên Bái',
    code: '15',
  },
  {
    name: 'Hoà Bình',
    slug: 'hoa-binh',
    type: 'tinh',
    name_with_type: 'Tỉnh Hoà Bình',
    code: '17',
  },
  {
    name: 'Thái Nguyên',
    slug: 'thai-nguyen',
    type: 'tinh',
    name_with_type: 'Tỉnh Thái Nguyên',
    code: '19',
  },
  {
    name: 'Lạng Sơn',
    slug: 'lang-son',
    type: 'tinh',
    name_with_type: 'Tỉnh Lạng Sơn',
    code: '20',
  },
  {
    name: 'Quảng Ninh',
    slug: 'quang-ninh',
    type: 'tinh',
    name_with_type: 'Tỉnh Quảng Ninh',
    code: '22',
  },
  {
    name: 'Bắc Giang',
    slug: 'bac-giang',
    type: 'tinh',
    name_with_type: 'Tỉnh Bắc Giang',
    code: '24',
  },
  {
    name: 'Phú Thọ',
    slug: 'phu-tho',
    type: 'tinh',
    name_with_type: 'Tỉnh Phú Thọ',
    code: '25',
  },
  {
    name: 'Vĩnh Phúc',
    slug: 'vinh-phuc',
    type: 'tinh',
    name_with_type: 'Tỉnh Vĩnh Phúc',
    code: '26',
  },
  {
    name: 'Bắc Ninh',
    slug: 'bac-ninh',
    type: 'tinh',
    name_with_type: 'Tỉnh Bắc Ninh',
    code: '27',
  },
  {
    name: 'Hải Dương',
    slug: 'hai-duong',
    type: 'tinh',
    name_with_type: 'Tỉnh Hải Dương',
    code: '30',
  },
  {
    name: 'Hải Phòng',
    slug: 'hai-phong',
    type: 'thanh-pho',
    name_with_type: 'Thành phố Hải Phòng',
    code: '31',
  },
  {
    name: 'Hưng Yên',
    slug: 'hung-yen',
    type: 'tinh',
    name_with_type: 'Tỉnh Hưng Yên',
    code: '33',
  },
  {
    name: 'Thái Bình',
    slug: 'thai-binh',
    type: 'tinh',
    name_with_type: 'Tỉnh Thái Bình',
    code: '34',
  },
  {
    name: 'Hà Nam',
    slug: 'ha-nam',
    type: 'tinh',
    name_with_type: 'Tỉnh Hà Nam',
    code: '35',
  },
  {
    name: 'Nam Định',
    slug: 'nam-dinh',
    type: 'tinh',
    name_with_type: 'Tỉnh Nam Định',
    code: '36',
  },
  {
    name: 'Ninh Bình',
    slug: 'ninh-binh',
    type: 'tinh',
    name_with_type: 'Tỉnh Ninh Bình',
    code: '37',
  },
  {
    name: 'Thanh Hóa',
    slug: 'thanh-hoa',
    type: 'tinh',
    name_with_type: 'Tỉnh Thanh Hóa',
    code: '38',
  },
  {
    name: 'Nghệ An',
    slug: 'nghe-an',
    type: 'tinh',
    name_with_type: 'Tỉnh Nghệ An',
    code: '40',
  },
  {
    name: 'Hà Tĩnh',
    slug: 'ha-tinh',
    type: 'tinh',
    name_with_type: 'Tỉnh Hà Tĩnh',
    code: '42',
  },
  {
    name: 'Quảng Bình',
    slug: 'quang-binh',
    type: 'tinh',
    name_with_type: 'Tỉnh Quảng Bình',
    code: '44',
  },
  {
    name: 'Quảng Trị',
    slug: 'quang-tri',
    type: 'tinh',
    name_with_type: 'Tỉnh Quảng Trị',
    code: '45',
  },
  {
    name: 'Thừa Thiên Huế',
    slug: 'thua-thien-hue',
    type: 'tinh',
    name_with_type: 'Tỉnh Thừa Thiên Huế',
    code: '46',
  },
  {
    name: 'Đà Nẵng',
    slug: 'da-nang',
    type: 'thanh-pho',
    name_with_type: 'Thành phố Đà Nẵng',
    code: '48',
  },
  {
    name: 'Quảng Nam',
    slug: 'quang-nam',
    type: 'tinh',
    name_with_type: 'Tỉnh Quảng Nam',
    code: '49',
  },
  {
    name: 'Quảng Ngãi',
    slug: 'quang-ngai',
    type: 'tinh',
    name_with_type: 'Tỉnh Quảng Ngãi',
    code: '51',
  },
  {
    name: 'Bình Định',
    slug: 'binh-dinh',
    type: 'tinh',
    name_with_type: 'Tỉnh Bình Định',
    code: '52',
  },
  {
    name: 'Phú Yên',
    slug: 'phu-yen',
    type: 'tinh',
    name_with_type: 'Tỉnh Phú Yên',
    code: '54',
  },
  {
    name: 'Khánh Hòa',
    slug: 'khanh-hoa',
    type: 'tinh',
    name_with_type: 'Tỉnh Khánh Hòa',
    code: '56',
  },
  {
    name: 'Ninh Thuận',
    slug: 'ninh-thuan',
    type: 'tinh',
    name_with_type: 'Tỉnh Ninh Thuận',
    code: '58',
  },
  {
    name: 'Bình Thuận',
    slug: 'binh-thuan',
    type: 'tinh',
    name_with_type: 'Tỉnh Bình Thuận',
    code: '60',
  },
  {
    name: 'Kon Tum',
    slug: 'kon-tum',
    type: 'tinh',
    name_with_type: 'Tỉnh Kon Tum',
    code: '62',
  },
  {
    name: 'Gia Lai',
    slug: 'gia-lai',
    type: 'tinh',
    name_with_type: 'Tỉnh Gia Lai',
    code: '64',
  },
  {
    name: 'Đắk Lắk',
    slug: 'dak-lak',
    type: 'tinh',
    name_with_type: 'Tỉnh Đắk Lắk',
    code: '66',
  },
  {
    name: 'Đắk Nông',
    slug: 'dak-nong',
    type: 'tinh',
    name_with_type: 'Tỉnh Đắk Nông',
    code: '67',
  },
  {
    name: 'Lâm Đồng',
    slug: 'lam-dong',
    type: 'tinh',
    name_with_type: 'Tỉnh Lâm Đồng',
    code: '68',
  },
  {
    name: 'Bình Phước',
    slug: 'binh-phuoc',
    type: 'tinh',
    name_with_type: 'Tỉnh Bình Phước',
    code: '70',
  },
  {
    name: 'Tây Ninh',
    slug: 'tay-ninh',
    type: 'tinh',
    name_with_type: 'Tỉnh Tây Ninh',
    code: '72',
  },
  {
    name: 'Bình Dương',
    slug: 'binh-duong',
    type: 'tinh',
    name_with_type: 'Tỉnh Bình Dương',
    code: '74',
  },
  {
    name: 'Đồng Nai',
    slug: 'dong-nai',
    type: 'tinh',
    name_with_type: 'Tỉnh Đồng Nai',
    code: '75',
  },
  {
    name: 'Bà Rịa - Vũng Tàu',
    slug: 'ba-ria-vung-tau',
    type: 'tinh',
    name_with_type: 'Tỉnh Bà Rịa - Vũng Tàu',
    code: '77',
  },
  {
    name: 'Hồ Chí Minh',
    slug: 'ho-chi-minh',
    type: 'thanh-pho',
    name_with_type: 'Thành phố Hồ Chí Minh',
    code: '79',
  },
  {
    name: 'Long An',
    slug: 'long-an',
    type: 'tinh',
    name_with_type: 'Tỉnh Long An',
    code: '80',
  },
  {
    name: 'Tiền Giang',
    slug: 'tien-giang',
    type: 'tinh',
    name_with_type: 'Tỉnh Tiền Giang',
    code: '82',
  },
  {
    name: 'Bến Tre',
    slug: 'ben-tre',
    type: 'tinh',
    name_with_type: 'Tỉnh Bến Tre',
    code: '83',
  },
  {
    name: 'Trà Vinh',
    slug: 'tra-vinh',
    type: 'tinh',
    name_with_type: 'Tỉnh Trà Vinh',
    code: '84',
  },
  {
    name: 'Vĩnh Long',
    slug: 'vinh-long',
    type: 'tinh',
    name_with_type: 'Tỉnh Vĩnh Long',
    code: '86',
  },
  {
    name: 'Đồng Tháp',
    slug: 'dong-thap',
    type: 'tinh',
    name_with_type: 'Tỉnh Đồng Tháp',
    code: '87',
  },
  {
    name: 'An Giang',
    slug: 'an-giang',
    type: 'tinh',
    name_with_type: 'Tỉnh An Giang',
    code: '89',
  },
  {
    name: 'Kiên Giang',
    slug: 'kien-giang',
    type: 'tinh',
    name_with_type: 'Tỉnh Kiên Giang',
    code: '91',
  },
  {
    name: 'Cần Thơ',
    slug: 'can-tho',
    type: 'thanh-pho',
    name_with_type: 'Thành phố Cần Thơ',
    code: '92',
  },
  {
    name: 'Hậu Giang',
    slug: 'hau-giang',
    type: 'tinh',
    name_with_type: 'Tỉnh Hậu Giang',
    code: '93',
  },
  {
    name: 'Sóc Trăng',
    slug: 'soc-trang',
    type: 'tinh',
    name_with_type: 'Tỉnh Sóc Trăng',
    code: '94',
  },
  {
    name: 'Bạc Liêu',
    slug: 'bac-lieu',
    type: 'tinh',
    name_with_type: 'Tỉnh Bạc Liêu',
    code: '95',
  },
  {
    name: 'Cà Mau',
    slug: 'ca-mau',
    type: 'tinh',
    name_with_type: 'Tỉnh Cà Mau',
    code: '96',
  },
  {
    name: 'Hà Nội',
    slug: 'ha-noi',
    type: 'thanh-pho',
    name_with_type: 'Thành phố Hà Nội',
    code: '01',
  },
  {
    name: 'Hà Giang',
    slug: 'ha-giang',
    type: 'tinh',
    name_with_type: 'Tỉnh Hà Giang',
    code: '02',
  },
  {
    name: 'Cao Bằng',
    slug: 'cao-bang',
    type: 'tinh',
    name_with_type: 'Tỉnh Cao Bằng',
    code: '04',
  },
  {
    name: 'Bắc Kạn',
    slug: 'bac-kan',
    type: 'tinh',
    name_with_type: 'Tỉnh Bắc Kạn',
    code: '06',
  },
  {
    name: 'Tuyên Quang',
    slug: 'tuyen-quang',
    type: 'tinh',
    name_with_type: 'Tỉnh Tuyên Quang',
    code: '08',
  },
]
